apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpressapp-db-pvc
  labels:
    app: wordpressapp
    tier: database
spec:
  # storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      app: wordpressapp
      tier: database