apiVersion: v1
kind: Secret
metadata:
  name: wp-database-cred
  labels:
    app: wordpressapp
    tier: database
data:
  MYSQL_ROOT_PASSWORD: Um9vdEAxMjM0NQ==
  MYSQL_DATABASE: d29yZHByZXNzd2Vi
  MYSQL_USER: c3VwZXI=
  MYSQL_PASSWORD: U3VwZXJAMTIzNDU=

