apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpressapp-mysql
  labels:
    app: wordpressapp
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpressapp 
      tier: database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpressapp
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306          
          envFrom:
            - secretRef:
                name: wp-database-cred
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: wordpressapp-database-volume
      volumes:
        - name: wordpressapp-database-volume
          persistentVolumeClaim:
            claimName: wordpressapp-db-pvc
