apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpressapp
    tier: database
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: wordpressapp
    tier: database