apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpressapp-web-pv
  labels:
    app: wordpressapp
    tier: web
spec:
  #storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Mi
  hostPath:
    path: /home/faisal/Documents/kubernetes/assignement1_wordpress_deployment/pv_folder
    type: Directory

# For EBs Volume
  # awsElasticBlockStore:
  #   volumeID: <volume-id>
  #   fsType: ext4

# Volume Modes:
# ReadOnlyMany
# ReadWriteOnce
# ReadWriteMany
