apiVersion: v1
kind: Service
metadata:
  name: wordpress-web
  labels:
      app: wordpressapp
      tier: web
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30020
  selector:
      app: wordpressapp
      tier: web



      